package: blogger
version: '1.3.3'

page:
  title: 'translate:title'
  perm: 'blogger[]'
  subpages:
    entries: { title: 'translate:page_entries' }
    categories: { title: 'translate:page_categories' }
    tags: { title: 'translate:page_tags' }
    config: { title: 'translate:page_config' }
